apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8s-namespace-guard
  name: k8s-namespace-guard
  namespace: default
spec:
  ports:
  - port: 443
    targetPort: 443
    name: https
  selector:
    app: k8s-namespace-guard
